services:
  client:
    image: nginx:alpine
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "80:80"
    # command: sh -c "npm install --legacy-peer-deps && npm run build"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./client/build:/opt/app
    depends_on:
      - server
  
  server:
    image: openjdk:17-alpine
    build: 
      context: ./server
    container_name: server
    working_dir: /server 
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    command: sh -c "
        chmod +x /server/gradlew &&
        /server/gradlew clean build --stacktrace &&
        cp /server/build/libs/server-0.0.1-SNAPSHOT.jar /server/app.jar &&
        java -jar /server/app.jar"
    ports:
      - "8000:8080"
    volumes:
      - ./server/:/server
    depends_on:
      db:
        condition: service_healthy

  nginx-rtmp:
    image: tiangolo/nginx-rtmp
    restart: always
    container_name: nginx-rtmp
    ports:
      - "1935:1935"  # RTMP
      - "8050:8050"  # HLS
    volumes:
      - ./nginx/rtmp.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./hls:/opt/data/hls

  db:
    image: mysql:8.0.30
    restart: always
    container_name: db
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    environment: 
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    platform: linux/x86_64
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 30s
      retries: 10
      start_period: 30s

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - ./redis:/redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1m30s
      timeout: 30s
      retries: 10
      start_period: 30s

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "9000:8080"
      - "50000:50000"
    volumes:
      - ./jenkins:/var/jenkins_home
      - ./jenkins/home:/var/jenkins_home/data
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    user: root