spring:
  config:
    activate:
      on-profile: prod
      
  datasource:
    url: jdbc:mysql://db:3306/vople?serverTimezone=UTC&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: never

  data:
    redis:
      host: redis
      port: 6379
    rtmp:
      host: rtmp://localhost:1935/live/
    hls:
      host-prefix: http://localhost:8050/hls/
      host-postfix: .m3u8
      
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: {your_client_id}
            client-secret: {your-client-secret}
            redirect-uri: http://localhost/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
            client-name: kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
springdoc:
  swagger-ui:
    path: /index.html
  api-docs:
    path: /v3/api-docs

base_url: http://localhost
kakao_login_url: http://localhost