spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:tcp://localhost/~/server
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
#      ddl-auto: update
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        id:
          new_generator_mappings: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  data:
    redis:
      host: localhost
      port: 6379
    rtmp:
      host: rtmp://i12b102.p.ssafy.io:1935/live/
    hls:
      host-prefix: http://i12b102.p.ssafy.io:8050/hls/
      host-postfix: .m3u8

paging:
  default-page-size: 10
  default-page-number: 0

logging.level:
  org.hibernate.SQL: DEBUG
  org.springframework:
    web.socket: DEBUG
    messaging: DEBUG

springdoc:
  swagger-ui:
    path: /index.html
  api-docs:
    path: /v3/api-docs


