server:
  port: 8080

spring:
  application:
    name: server
  datasource:
    # url: jdbc:mysql://db:3306/vople?serverTimezone=UTC&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/vople?serverTimezone=UTC&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create
        dialect: org.hibernate.dialect.MySQLDialect
  devtools:
    livereload:
      enabled: true
    freemarker:
      cache: false
  logging:
    level:
      org.springframework.boot.autoconfigure.security: TRACE
      org.springframework.security: DEBUG
      com.votegaheneta: DEBUG