spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:tcp://localhost/~/server
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

paging:
    default-page-size: 10
    default-page-number: 0

logging.level:
  org.hibernate.SQL: DEBUG
  org.springframework:
    web.socket: DEBUG
    messaging: DEBUG

