spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://db:3306/vople?serverTimezone=UTC&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        ddl-auto: create
        dialect: org.hibernate.dialect.MySQLDialect
